name: Deploy to Remote Server

on:
  push:
    branches:
      - master  # 仅当代码推送到 master 分支时触发
    tags:
      - 'v*'  # 仅当推送的是以 "v" 开头的 tag 时触发

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 GitHub 提供的最新 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: hollow288/ocr-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
  #Todo 自动部署这一部分有问题,未解决,貌似是SSH连接时出现了问题
  deploy:
    runs-on: ubuntu-latest

    needs: build  # 需要在构建镜像后才执行部署

    # 只有在标签是以 "v" 开头的版本时才会执行
    if: startsWith(github.ref, 'refs/tags/v')  # 检查是否是以 "v" 开头的标签

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: appleboy/ssh-action@v1.2.0  # 使用 SSH 连接远程服务器
        with:
          host: ${{ secrets.SERVER_IP }}  # 远程服务器 IP 地址，使用 GitHub Secrets
          username: ${{ secrets.SERVER_USER }}  # 远程服务器用户名，使用 GitHub Secrets
          key: ${{ secrets.SERVER_SSH_KEY }}  # SSH 密钥，使用 GitHub Secrets
          port: 22  # 如果使用非标准端口，修改端口号

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
          docker pull hollow288/nonebot-docker:latest &&
          docker stop nonebot-container &&
          docker rm nonebot-container &&
          docker run -d --name nonebot-container -p 8080:8080 -v /opt/nonebot/.env:/app/.env hollow288/nonebot-docker:latest
          "